# Configuration file for experimentation, Kubernetes cluster, pod settings and experimentation settings

# Configuration of experimentation

expe_duration: 25 # Duration of the experimentation in seconds
pods_interval: 1 # Average time to wait between the generation of pods
min_number_per_interval: 10 # Lowest number of pods that can be generated for a given pods_interval
max_number_per_interval: 14 # Highest number of pods that can be generated for a given pods_interval
game_interval: 0.5 # Average time to wait between two games
reproductible_seed: DrLeoandMrStef # Seeding the PRNG for reproductibility in datasets and nodes/pods attributions

# Configuration for Kubernetes
namespace: expe
disk_size: 80000  # Disk size in MB => equally shared between nodes
nodes_number: 4  # Number of nodes in the cluster
memory: 16000 # RAM per node in MB
cpus: 4  # Number of CPU cores per node

# Configuration for experimentations results

pods_dataset_file: pods_dataset.csv
results_file_nodes: plots/results/data_nodes.csv
results_file_pods: plots/results/data_pods.csv
ran_dataset: ran_dataset.csv

# Configuration for pods. Selected pods : https://zenodo.org/records/3974220

pods_config:
  - name: aeneas-pod
    CPU: 240  # Set of CPU values in milli CPUs
    RAM: 1500   # Set of RAM values in Mi
    storage: 900  # Storage capacity for the nginx pod in MB
    transmission_uplink: 427344 # bits to transmit over RAN (Bits)
    transmission_downlink: 816
    instructions: 54271527 # Real value : 8807684292 # number of instructions to be done
    deadline: 55 # Maximum delay for this app
  - name: julius-pod
    CPU: 250  
    RAM: 1000  
    storage: 800 
    transmission_uplink: 160096
    transmission_downlink: 9032 
    instructions: 24271527 # Real value : 100141000000 ; Usually Used
    deadline: 60  
  - name: mrleo-pod
    CPU: 350 
    RAM: 2500  
    storage: 1800 
    transmission_uplink: 41000
    transmission_downlink: 41000
    instructions: 14271527 # Real value : 544271527
    deadline: 33
#  - name: edgestorage-pod
#    CPU: 20 
#    RAM: 20  
#    storage: 1000 # 1Go
#     transmission_uplink: 1000000 
#    transmission_downlink: 1000000
#    instructions: 10 # Not instructions only data transfer
#    deadline: 33 
   
# Configuration for nodes. Verify that the names used really corresponds to the names defined by Minikube.
nodes_config:
  # Node 1
  - id: minikube
    CPU_percentage: 0.25
    RAM_percentage: 0.25
    storage_percentage: 0.25
    selfish-ratio: 0.5
    average-processing-delay:
      - pod-name: aeneas-pod
        bu: 6470
        gu: 7870
        be: 8410
      - pod-name: julius-pod
        bu: 5980
        gu: 5600
        be: 5500
      - pod-name: mrleo-pod
        bu: 5400
        gu: 5600
        be: 5380
    connections:
      - target_node: minikube-m02
        latency: 20 # Delay in ms
        bandwidth: 1250 # Bandwidth in MB per second
      - target_node: minikube-m03
        latency: 30 # Delay in ms
        bandwidth: 1250 # Bandwidth in MB per second
      - target_node: minikube-m04
        latency: 25 # Delay in ms
        bandwidth: 1250 # Bandwidth in MB per second
  - id: minikube-m02
    CPU_percentage: 0.25
    RAM_percentage: 0.25
    storage_percentage: 0.25
    selfish-ratio: 0.5
    average-processing-delay:
      - pod-name: aeneas-pod
        bu: 7050
        gu: 8200
        be: 8610
      - pod-name: julius-pod
        bu: 6200
        gu: 5800
        be: 6000
      - pod-name: mrleo-pod
        bu: 5800 
        gu: 5400
        be: 5210
    connections:
      - target_node: minikube
        latency: 20 
        bandwidth: 1250
      - target_node: minikube-m03
        latency: 20
        bandwidth: 1250
      - target_node: minikube-m04
        latency: 20 
        bandwidth: 1250
  - id: minikube-m03
    CPU_percentage: 0.25
    RAM_percentage: 0.25
    storage_percentage: 0.25
    selfish-ratio: 0.5
    average-processing-delay:
      - pod-name: aeneas-pod
        bu: 7090
        gu: 8100
        be: 8680
      - pod-name: julius-pod
        bu: 5900
        gu: 5700
        be: 5900
      - pod-name: mrleo-pod
        bu: 5700 
        gu: 5300
        be: 5290
    connections:
      - target_node: minikube
        latency: 30 
        bandwidth: 1250 
      - target_node: minikube-m02
        latency: 20 
        bandwidth: 1250
      - target_node: minikube-m04
        latency: 40 
        bandwidth: 1250
  - id: minikube-m04
    CPU_percentage: 0.25
    RAM_percentage: 0.25
    storage_percentage: 0.25
    selfish-ratio: 0.75
    average-processing-delay:
      - pod-name: aeneas-pod
        bu: 7090
        gu: 8100
        be: 8680
      - pod-name: julius-pod
        bu: 5900
        gu: 5700
        be: 5900
      - pod-name: mrleo-pod
        bu: 5700 
        gu: 5300
        be: 5290
    connections:
      - target_node: minikube
        latency: 25 
        bandwidth: 1250 
      - target_node: minikube-m02
        latency: 20 
        bandwidth: 1250
      - target_node: minikube-m03
        latency: 40 
        bandwidth: 1250
  # Node X
